### PR TITLE
Support Intel QAT

### PR DESCRIPTION
**Pull request by oracle219**
## Support Intel QAT and asynchronous module, base OpenResty-1.13.6.1 release([added support for OpenSSL 1.1.0 feature](https://github.com/openresty/lua-nginx-module/commit/7f108923b01e32718b98f37ef824f1383de5c49c)).
- Build OpenResty like this:
```
./configure --prefix=/usr/local/openresty \
            --with-luajit \
            --with-http_iconv_module \
            --with-http_realip_module \
            --with-http_stub_status_module \
            --with-http_ssl_module \
            --with-cc-opt="-DNGX_SECURE_MEM -I/usr/local/ssl/include -Wno-error=deprecated-declarations" \
            --with-ld-opt="-Wl,-rpath=/usr/local/ssl/lib -L/usr/local/ssl/lib"
gmake
gmake install
```
- For example, edit conf/nginx.conf
```
http {
    ……
    server {
        ssl_asynch  on;
        ……
        }
    }
}
```
- About build OpenSSL, QAT driver and QAT engine, see also
https://github.com/intel/QAT_Engine#installation-instructions
https://01.org/sites/default/files/page/330751-006_clc_pg.pdf

### CODE REVIEW

**Comment by agentzh** [comment]
@oracle219 Did you write this patch yourself or you just stole it from somewhere else? What's the original source of this patch?

**Comment by oracle219** [comment]
@agentzh patch refer to https://01.org/intel-quickassist-technology/intel-quick-assist-technology/downloads/nginx-sample-patch-intel®-quickassist-technology-1.10.3.l.0.3.1-001. but this patch base nginx-1.10, need some fix.

**Comment by agentzh** [comment]
@oracle219 I'm not sure what license this patch is under. It's not clear to me. Will you confirm?

This patch is very sloppy in its current shape.

**Comment by oracle219** [comment]
@agentzh see Tengine new feature is also support Intel QAT, https://github.com/alibaba/tengine/releases.

**Comment by agentzh** [comment]
@oracle219 What's the point? You want to use Tengine as an example for merging sloppy and badly shaped patch in OpenResty? I don't follow your reasoning here. Sorry.

**Comment by agentzh** [comment]
@oracle219 The thing is that we must do things right. It's a very serious matter. OpenResty is a not a playground of dirty hacks. Every patch that gets merged must in a good shape and pass our comprehensive code review and testing process.

**Comment by agentzh** [comment]
@oracle219 Also, the license and terms of every line of the new code must be clear. This is about legal issues and must be taken into account very seriously.

**Pull request closed without merging**
