### PR TITLE
Add a --without-any-lua configure option

### PR DESCRIPTION
**Pull request by leto**
This is related to #105

### CODE REVIEW

**Comment by agentzh** [comment]
Hmm, seems like we also need to disable LuaJIT. Before that, we need to have a `--without-luajit` option. Thoughts?

**Comment by leto** [comment]
@agentzh I can add that too! Would you prefer it be in this PR or a different one?

**Comment by agentzh** [comment]
@leto Either is fine :) Thanks!

**Comment by agentzh** [comment]
@leto I have a mixed feeling about this. Is an OpenResty without any Lua still OpenResty?

**Comment by bungle** [comment]
This is for advanced users, and having a config option(s) to disable things is well, just flexible. I'm against having `--without-any-lua`. You can disable them one-by-one, :-). If you disable/remove Lua altogether, maybe then you are prohibited to call it OpenResty anymore?

**Comment by leto** [comment]
My original reason for this was that I used OpenResty for a non-Lua project, since it makes it so easy to  use various add-ons. I was mostly using rds_json and postgres modules to implement a JSON API directly in Nginx/OpenResty, without any dynamic language. It was extremely performant.

You can think of this as an "easy on-ramp" for people to use and get interesting in OpenResty without Lua. I ended up having 20 ``--without`` statements in my provision scripts to compile OpenResty, which is why I suggested ```--without-any-lua```.

**Comment by bungle** [comment]
@leto,

I know, `without-any-lua` sounds a bit harsh, maybe:

```
--without-lua-libraries
```

Is a bit better. That could include all `lua-resty-*`and `lua-cjson` and `lua-rds-parser`.

And possibly (these are rather static though):

```
--without-lua-modules
```

**Comment by agentzh** [comment]
@leto @bungle  I think a better approach is to automatically exclude all the Lua libraries and the ngx_http_lua_upstream module when the user specifies the `--without-http_lua_module` option. This looks more reasonable to me. What do you guys think?

**Comment by bungle** [comment]
@agentzh, that's even better. Doesn't get any easier than than.

**Comment by agentzh** [comment]
Patches welcome! Volunteers welcome! :)

**Comment by bungle** [comment]
@leto, would you like to modify your patch so that `--without-http_lua_module` disables all the Lua-related?

**Comment by leto** [comment]
@bungle yep, gonna work on it today!

**Pull request closed without merging**
