### PR TITLE
support to add relative path dynamic-module in configure

### PR DESCRIPTION
**Pull request by catatsuy**
I hereby granted the copyright of the changes in this pull request
to the authors of this openresty project.

### CODE REVIEW

**Comment by agentzh** [comment]
@catatsuy Looking good to me. Mind to add a test case to the existing test suite to cover this new feature? Thanks!

**Comment by shadowz10** [comment]
@agentzh  Hello, I would like to translate to Spanish but I do not know how. I would like to do it by means of pull request :)

**Comment by agentzh** [comment]
@shadowz10 Please do not hijack unrelated PRs or issues. Thank you.

**Comment by agentzh** [comment]
@catatsuy Sorry for the delay on my side. Just merged it with fixes for the test failures.

**Comment by agentzh** [comment]
Thanks!

**Comment by catatsuy** [comment]
Thank you!

**Pull request closed without merging**
