### PR TITLE
optimize: configure generate more elegant lib info

### PR DESCRIPTION
**Pull request by alues**
Before
```bash
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.1.0j  20 Nov 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-threads --with-pcre-jit --with-http_v2_module --with-http_addition_module --with-http_auth_request_module 
--with-openssl=/root/OpenResty/openresty-1.15.8.1/openssl-1.1.0j --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module
```
After:
```bash
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.1.0k  28 May 2019
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-threads --with-pcre-jit --with-http_v2_module --with-http_addition_module --with-http_auth_request_module --with-pcre=../pcre-8.43 
--with-openssl=../openssl-1.1.0k --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module
```

I hereby granted the copyright of the changes in this pull request
to the authors of this openresty project.

### CODE REVIEW

**Comment by alues** [comment]
@thibaultcha @agentzh any comment?

**Comment by thibaultcha** [comment]
@alues Hi, thanks for the patch. Please allow for some time before we can look at it, as we are busy on other projects and on preparing the upcoming release at the moment. Thanks!

**Comment by thibaultcha** [comment]
Keeping the absolute path is much more valuable imho, I can't say that I am in favor of this change.

**Comment by alues** [comment]
@thibaultcha Once the end user has extracted these libraries into the bundle folder, these libraries should be registered as internal libraries. 
The absolute bundle libraries path in `nginx -V` doesn't seem to be a good idea. It may confuse end user.
Any comment or close PR. thx.

**Comment by agentzh** [comment]
I don't like this change either. Sorry. Closing it.

**Pull request closed without merging**
