### PR TITLE
patches: ensure "server" header in HTTP/2 response shows "openresty"

### PR DESCRIPTION
**Pull request by dndx**
when server_tokens are turned off.

I hereby granted the copyright of the changes in this pull request
to the authors of this openresty project.

### CODE REVIEW

**Comment by agentzh** [comment]
@dndx I think we just need the patch for nginx 1.13.5, no earlier versions needed.

**Comment by dndx** [comment]
@agentzh Added. I think we can just keep the changes to older versions as they are not harmful anyway.

**Comment by agentzh** [comment]
@dndx Fine.

**Comment by agentzh** [comment]
@dndx Seems like you forgot to update `util/mirror-tarballs` to actually apply the patch?

**Comment by dndx** [comment]
@agentzh We are updating an existing patch so no need to change `util/mirror-tarballs.

**Comment by agentzh** [comment]
@dndx Merged. Thanks!

**Pull request closed without merging**
